<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@ page import="java.util.*" %>
<%!
private String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%>
<%
int id=-1;try{id=Integer.parseInt(request.getParameter("id"));}catch(Exception ignored){}
Map<String,Object> problem=com.contest.data.ProblemDatabase.getProblem(id);
if(problem==null){response.sendError(404,"Problem not found");return;}
String casesJson=new com.google.gson.Gson().toJson(problem.get("testCases"));
%>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit <%=esc(String.valueOf(problem.get("title")))%> — CodeArena Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<%=request.getContextPath()%>/assets/site.css" rel="stylesheet"><style>body{background:#f5f5f1}.edit-wrap{max-width:1050px;padding:38px 28px}.edit-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:24px}.edit-head h1{font-size:28px;letter-spacing:-1px}.edit-card{background:#fff;border:1px solid #e7e7e0;border-radius:10px;padding:24px}.edit-card .form-label{font-size:12px;font-weight:700}.edit-card .form-control,.edit-card .form-select{font-size:13px}.save-row{display:flex;justify-content:space-between;align-items:center;margin-top:22px}@media(max-width:600px){.edit-wrap{padding:24px 14px}.edit-card{padding:17px}.edit-head h1{font-size:23px}}</style></head><body><div class="container-fluid edit-wrap"><div class="edit-head"><div><div class="text-uppercase text-secondary small mb-2">Problem library · #<%=id%></div><h1>Edit problem</h1><p class="text-secondary mb-0">Update the statement, examples, and hidden judge cases. Changes appear in assigned contests immediately.</p></div><a class="btn btn-outline-secondary" href="<%=request.getContextPath()%>/admin/manage-problems.jsp">← Back to problems</a></div>
<%if(request.getAttribute("errorMsg")!=null){%><div class="alert alert-danger"><%=esc(String.valueOf(request.getAttribute("errorMsg")))%></div><%}%>
<form class="edit-card" action="<%=request.getContextPath()%>/manageProblem" method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<%=id%>">
<div class="row"><div class="col-md-8 mb-3"><label class="form-label">Problem title</label><input class="form-control" name="title" required maxlength="160" value="<%=esc(String.valueOf(problem.get("title")))%>"></div><div class="col-md-4 mb-3"><label class="form-label">Category</label><input class="form-control" name="category" value="<%=esc(String.valueOf(problem.get("category")))%>"></div></div>
<div class="mb-3"><label class="form-label">Problem statement</label><textarea class="form-control" name="description" rows="5" required><%=esc(String.valueOf(problem.get("description")))%></textarea></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Input format</label><textarea class="form-control" name="inputFormat" rows="3"><%=esc(String.valueOf(problem.get("inputFormat")))%></textarea></div><div class="col-md-6 mb-3"><label class="form-label">Output format</label><textarea class="form-control" name="outputFormat" rows="3"><%=esc(String.valueOf(problem.get("outputFormat")))%></textarea></div></div>
<div class="row"><div class="col-md-8 mb-3"><label class="form-label">Constraints</label><textarea class="form-control" name="constraints" rows="3"><%=esc(String.valueOf(problem.get("constraints")))%></textarea></div><div class="col-md-2 mb-3"><label class="form-label">Difficulty</label><select class="form-select" name="difficulty"><%String currentDifficulty=String.valueOf(problem.get("difficulty"));for(String d:new String[]{"Easy","Medium","Hard"}){%><option value="<%=d%>" <%if(d.equals(currentDifficulty)){%>selected<%}%>><%=d%></option><%}%></select></div><div class="col-md-2 mb-3"><label class="form-label">Points</label><input class="form-control" type="number" min="1" max="10000" name="points" value="<%=esc(String.valueOf(problem.get("points")))%>" required></div></div>
<div class="mb-3"><label class="form-label">Test cases (JSON)</label><textarea class="form-control font-monospace" name="testCases" rows="9" required><%=esc(casesJson)%></textarea><div class="form-text">Each item needs input, output, and optional hidden (true/false). Hidden cases are judged on submission but are never shown to participants.</div></div>
<div class="save-row"><span class="text-muted small">ID <%=id%> stays the same, so existing contest assignments remain intact.</span><button class="btn btn-primary px-4" type="submit">Save changes</button></div></form></div></body></html>
