<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.util.*" %>
<% String ctx = request.getContextPath(); %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CodeArena — Think. Build. Compete.</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="<%=ctx%>/assets/site.css" rel="stylesheet">
</head>
<body class="landing">
<header class="topbar">
  <a class="brand" href="<%=ctx%>/index.jsp"><span class="brand-mark">&lt;/&gt;</span> codearena<span class="brand-dot">.</span></a>
  <nav class="topnav">
    <a href="<%=ctx%>/user/problems.jsp">Problems</a>
    <a href="<%=ctx%>/user/contest-dashboard.jsp">Contests</a>
    <a href="#how">How it works</a>
  </nav>
  <div class="top-actions">
    <a class="admin-link" href="<%=ctx%>/admin/dashboard.jsp">Admin Portal <span>↗</span></a>
    <a class="button button-dark button-small" href="<%=ctx%>/user/problems.jsp">Solve Problems <span>→</span></a>
  </div>
</header>
<main>
  <section class="hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="live-dot"></span> THE ARENA IS OPEN <span class="eyebrow-divider">/</span> SEASON 04</div><h1>Good code.<br><span>Great instincts.</span></h1><p class="hero-lede">A place to sharpen your thinking, take on real challenges, and see how you stack up. Your next breakthrough starts with one problem.</p><div class="hero-actions"><a class="button button-lime" href="<%=ctx%>/user/problems.jsp">Browse All Problems <span>↗</span></a><a href="#how" class="text-link">See how it works <span>↓</span></a></div><div class="hero-proof"><div class="avatar-stack"><i>J</i><i>M</i><i>A</i><i>+</i></div><span><strong>Built for curious minds.</strong><br>Show up, solve something, grow.</span></div></div>
  <div class="hero-art"><div class="art-glow"></div><div class="editor-card"><div class="editor-head"><div class="window-dots"><b></b><b></b><b></b></div><span>two-sum.py</span><span class="editor-lang">PYTHON 3</span></div><div class="code-lines"><div><em>01</em><span><i>def</i> <strong>two_sum</strong>(nums, target):</span></div><div><em>02</em><span class="indent"><i>seen</i> = {}</span></div><div><em>03</em><span class="indent"><i>for</i> i, n <i>in</i> <strong>enumerate</strong>(nums):</span></div><div><em>04</em><span class="indent2">if target - n in seen:</span></div><div><em>05</em><span class="indent3"><b>return</b> [seen[target - n], i]</span></div><div><em>06</em><span class="indent"><i>seen</i>[n] = i</span></div><div class="cursor-row"><em>07</em><span class="indent"><b>return</b> []<span class="cursor"></span></span></div></div><div class="editor-foot"><span><b class="pass-dot"></b> All tests passed</span><span>0.04s <span class="sep">·</span> 12.8 MB</span></div></div><div class="float-chip chip-score"><span class="chip-icon">✳</span><div><small>YOUR BEST</small><strong>+240 <small>pts</small></strong></div></div><div class="float-chip chip-streak"><span>↗</span> Keep the streak alive</div><div class="hero-index">01 <span>/</span> 03</div></div></section>
  <section class="ticker"><div class="ticker-inner"><span>THINK IN ALGORITHMS</span><b>✳</b><span>BUILD WITH PURPOSE</span><b>✳</b><span>COMPETE WITH HEART</span><b>✳</b><span>THINK IN ALGORITHMS</span><b>✳</b><span>BUILD WITH PURPOSE</span><b>✳</b><span>COMPETE WITH HEART</span></div></section>
  <section id="contests" class="section wrap"><div class="section-heading"><div><div class="eyebrow">01 <span class="eyebrow-divider">/</span> FIND YOUR PEOPLE</div><h2>Challenges worth<br>showing up for<span class="brand-dot">.</span></h2></div><a href="<%=ctx%>/user/contest-dashboard.jsp" class="text-link">Browse all contests <span>↗</span></a></div><div class="contest-grid"><article class="contest-card featured"><div class="contest-art art-purple"><div class="orb orb-one"></div><div class="orb orb-two"></div><span class="contest-issue">WEEKLY SERIES <b>04</b></span><span class="art-symbol">{ }</span></div><div class="contest-body"><div class="contest-meta"><span class="pill pill-live"><i></i> OPEN NOW</span><span>⏱ &nbsp;2 hours</span></div><h3>The Sunday Sprint</h3><p>Five problems. One leaderboard. A fresh start every week.</p><div class="contest-bottom"><div class="mini-avatars"><i>AK</i><i>SR</i><i>+128</i></div><a href="<%=ctx%>/user/contest-dashboard.jsp" class="round-arrow">↗</a></div></div></article><article class="contest-card"><div class="contest-art art-orange"><div class="sun"></div><span class="contest-issue">BEGINNER FRIENDLY <b>01</b></span><span class="art-symbol">01</span></div><div class="contest-body"><div class="contest-meta"><span class="pill pill-soon">STARTS SOON</span><span>⏱ &nbsp;45 min</span></div><h3>First Steps</h3><p>Small wins, satisfying problems. Perfect for your first contest.</p><div class="contest-bottom"><div class="mini-avatars"><i>TP</i><i>ML</i><i>+42</i></div><a href="<%=ctx%>/user/contest-dashboard.jsp" class="round-arrow">↗</a></div></div></article><article class="contest-card"><div class="contest-art art-green"><div class="grid-art"></div><span class="contest-issue">ADVANCED <b>08</b></span><span class="art-symbol">∑</span></div><div class="contest-body"><div class="contest-meta"><span class="pill pill-open">JOIN ANYTIME</span><span>⏱ &nbsp;3 hours</span></div><h3>Graph Theory Lab</h3><p>Put your shortest paths and spanning trees to work.</p><div class="contest-bottom"><div class="mini-avatars"><i>NK</i><i>DV</i><i>+76</i></div><a href="<%=ctx%>/user/contest-dashboard.jsp" class="round-arrow">↗</a></div></div></article></div></section>
  <section id="how" class="how-section"><div class="wrap how-grid"><div><div class="eyebrow">02 <span class="eyebrow-divider">/</span> YOUR NEXT MOVE</div><h2>Simple to start.<br><span>Hard to put down.</span></h2><p class="muted-copy">No complicated setup. Just you, a good problem, and the satisfying moment when it clicks.</p><a class="button button-dark" href="<%=ctx%>/user/problems.jsp">Explore Problem Set <span>→</span></a></div><div class="steps"><article><div class="step-num">01</div><div><h3>Pick a challenge</h3><p>Find the right pace, topic, and level for where you are today.</p></div><span class="step-symbol">◎</span></article><article><div class="step-num">02</div><div><h3>Think it through</h3><p>Work in a focused coding space with examples and instant feedback.</p></div><span class="step-symbol">⌘</span></article><article><div class="step-num">03</div><div><h3>Watch yourself grow</h3><p>Track your progress, climb the board, and come back stronger.</p></div><span class="step-symbol">↗</span></article></div></div></section>
  <section id="problems" class="practice-section wrap"><div class="practice-copy"><div class="eyebrow">03 <span class="eyebrow-divider">/</span> THE PRACTICE ROOM</div><h2>One good problem<br>can change your day<span class="brand-dot">.</span></h2><p>Browse the library, find a problem that makes you think, and solve it at your own pace. The best way forward is one small step.</p><a class="text-link" href="<%=ctx%>/user/problems.jsp">Explore the problem set <span>↗</span></a></div><div class="problem-preview"><div class="preview-top"><span>START WITH A CLASSIC</span><span>01</span></div><a class="preview-row" href="<%=ctx%>/user/coding-page.jsp?id=101"><span class="preview-num">01</span><span class="preview-title">Two Sum <small>ARRAYS · HASH MAPS</small></span><span class="difficulty easy">EASY</span><span class="preview-arrow">↗</span></a></div></section>
  <section class="cta-band"><div class="wrap cta-inner"><div><div class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h2>Ready when you are<span>.</span></h2></div><a class="button button-lime" href="<%=ctx%>/user/problems.jsp">Start Practicing <span>↗</span></a><span class="cta-mark">&lt;?&gt;</span></div></section>
</main><footer class="footer wrap"><a class="brand" href="<%=ctx%>/index.jsp"><span class="brand-mark">&lt;/&gt;</span> codearena<span class="brand-dot">.</span></a><span>Made for the love of solving things.</span><a href="<%=ctx%>/admin/dashboard.jsp">Platform admin ↗</a><span>© 2026 CodeArena</span></footer>
</body></html>
